# Generated by Django 4.2.30 on 2026-06-13 18:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('imported_rows', models.IntegerField(default=0)),
                ('skipped_rows', models.IntegerField(default=0)),
                ('flagged_rows', models.IntegerField(default=0)),
                ('auto_fixed_rows', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('is_permanent', models.BooleanField(default=False, help_text='True for permanent roommates, False for guests/temporary people')),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('left_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', max_length=3)),
                ('split_type', models.CharField(blank=True, choices=[('equal', 'Equal'), ('unequal', 'Unequal'), ('percentage', 'Percentage'), ('share', 'Share')], max_length=20, null=True)),
                ('split_with_raw', models.TextField(blank=True, default='', help_text='Raw split_with from CSV')),
                ('split_details_raw', models.TextField(blank=True, default='', help_text='Raw split_details from CSV')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_settlement', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('original_row', models.IntegerField(help_text='Row number in original CSV (1-indexed, header=1)')),
                ('raw_data', models.JSONField(default=dict, help_text='Original CSV row data')),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expenses.importsession')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_paid', to='expenses.person')),
            ],
            options={
                'ordering': ['date', 'original_row'],
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('anomaly_type', models.CharField(choices=[('duplicate', 'Duplicate Entry'), ('malformed_date', 'Malformed Date'), ('missing_currency', 'Missing Currency'), ('zero_amount', 'Zero Amount'), ('negative_amount', 'Negative Amount'), ('mixed_currency', 'Mixed Currency in Group'), ('settlement_row', 'Settlement Row'), ('split_mismatch', 'Split Type Mismatch'), ('missing_split_person', 'Missing Person in Split Details'), ('ambiguous_date', 'Ambiguous Date'), ('guest_person', 'Guest/Temporary Person'), ('case_inconsistency', 'Case Inconsistency'), ('missing_payer', 'Missing Payer'), ('possible_duplicate_log', 'Possible Duplicate Log'), ('percentage_incomplete', 'Incomplete Percentages'), ('departed_person', 'Departed Person in Split'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], max_length=10)),
                ('description', models.TextField()),
                ('action_taken', models.CharField(choices=[('skipped', 'Skipped'), ('flagged', 'Flagged'), ('auto_fixed', 'Auto-Fixed'), ('normalized', 'Normalized'), ('imported_as_is', 'Imported As-Is')], max_length=20)),
                ('original_value', models.TextField(blank=True, default='')),
                ('fixed_value', models.TextField(blank=True, default='')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='expenses.expense')),
                ('import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='expenses.importsession')),
            ],
            options={
                'verbose_name_plural': 'Anomalies',
                'ordering': ['row_number', 'anomaly_type'],
            },
        ),
        migrations.CreateModel(
            name='SplitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Calculated amount this person owes for this expense', max_digits=12)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage share if split_type is percentage', max_digits=5, null=True)),
                ('share_units', models.DecimalField(blank=True, decimal_places=2, help_text='Share units if split_type is share', max_digits=5, null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='expenses.expense')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_details', to='expenses.person')),
            ],
            options={
                'ordering': ['person__name'],
                'unique_together': {('expense', 'person')},
            },
        ),
    ]
